### ISSUE TITLE
cool stuff

### ISSUE THREAD

**Issue by ChillerDragon** [qianxyz/rplace#1]
found you in the aoc leaderboard :D 

I always wanted to host some r/place but never managed to finish [mine](https://github.com/ChillerDragon/rplace-sinatra).
The project was smooth to setup and it works really well. I have an instance running at https://place.zillyhuhn.com/ now :partying_face: 

The only trap was to make websockets work with apache. It needed ``ProxyPass /ws ws://localhost:8080/ws``

This is my full apache config in case anyone ever needs it :D 

```
<VirtualHost *:80>
    ServerAdmin invalid@zillyhuhn.com
    ServerName place.zillyhuhn.com
    Redirect / https://place.zillyhuhn.com
</VirtualHost>

<IfModule mod_ssl.c>
<VirtualHost *:443>
    ServerAdmin invalid@zillyhuhn.com
    ServerName place.zillyhuhn.com
    ProxyPreserveHost On

    # setup the proxy
    <Proxy *>
        Order allow,deny
        Allow from all
    </Proxy>
    SSLProxyEngine On
    SSLProxyCheckPeerCN on
    SSLProxyCheckPeerExpire on

    ProxyPreserveHost On
    ProxyRequests Off
    ProxyPass /ws ws://localhost:8080/ws

    ProxyPass / http://localhost:8080/ Keepalive=On
    ProxyPassReverse / http://localhost:8080/ Keepalive=On

    ServerAlias www.place.zillyhuhn.com
    SSLCertificateFile /etc/letsencrypt/live/zillyhuhn.com-0001/fullchain.pem
    SSLCertificateKeyFile /etc/letsencrypt/live/zillyhuhn.com-0001/privkey.pem
</VirtualHost>
</IfModule>
```

**Comment by qianxyz** [comment]
Thanks for the info, and [here](https://stackoverflow.com/questions/12102110/nginx-to-reverse-proxy-websockets-and-enable-ssl-wss) is more reference for people using NGINX. And you'd probably want some rate limiting at that level too since it's not implemented in the backend.

As for the AoC leaderboard, I apologize for using AI and not reading the [FAQ](https://adventofcode.com/2024/about#faq_ai_leaderboard) on this. Sorry for anyone who's competing on this, I've learned my lesson and won't be doing that again. Don't be like me.

**Comment by ChillerDragon** [comment]
Oh I did not know you used AI. I was hoping try hard humans were still faster than AI code generation. At least for the easy challenges.
